### ISSUE TITLE
Invert_Comm_Map should communicate data size to be exchanged

### ISSUE THREAD

**Issue by lowrie** [losalamos/Draco#103]
c4's Invert_Comm_Map currently takes a std::vector<int> as input and output arguments, which are the vector of procs that the current proc will send/receive information to/from.  Instead, it should take a std::map<int, size_t>, that maps proc number to the data size to be sent/received.  Here, "size" is up to the user; it could be the number of elements in a container, or the actual number of bytes; it doesn't matter to this routine.

This change should give a very small decrease in performance, because size_t values would be communicated, instead of int values.  But it would allow users to eliminate the extra communication step of determining the size of information to be received.

**Comment by alexrlongne** [comment]
I agree. Then instead of writing a "1" with RMA operations for a flag in the invert comm map routine you can just write the size (or number of elements) that should be received from that rank.
